AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
  DisplayCopNames: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Layout/LineLength:
  Max: 120
Security/Eval:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
